language:
 - python
python:
  - "3.6"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE test_db;'
install:
  - pip install -r requirements.txt
script:
  - python manage.py migrate
addons:
    apt:
        packages:
            - sshpass
after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && .
    - export SSHPASS=$dev_pass
    - sshpass -e ssh $dev_user@$dev_host /home/$dev_user/write.sh