language:
 - python
python:
  - "3.6"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE django;'
install:
  - pip install -r requirements.txt
script:
  - python manage.py migrate
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: sh scripts/deploy.sh dev
    on:
      branch: development
  # deploy master to production
  - provider: script
    script: sh scripts/deploy.sh prod
    on:
      branch: master
