language:
 - python
python:
  - "3.6"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE test_db;'
install:
  - pip install -r requirements.txt
script:
  - python manage.py migrate
addons:
    apt:
        packages:
            - sshpass
deploy:
  - provider: script
    script: sh scripts/deploy.sh
    on:
      branch: development
  - provider: script
    script: sh scripts/deploy.sh
    on:
      branch: master
