# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='active',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='bonuses',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='checkpoints',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='difficulty',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='enable_baked_triggers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='prevent_prehop',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='type',
            field=models.IntegerField(blank=True),
        ),
    ]
